#!/bin/sh
# Read the river, riverctl, and rivertile man pages.

# Use the "logo" key as the primary modifier
mod="Mod4"
mod1="Mod1"
riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"

# Open alacritty
riverctl map normal $mod Return spawn alacritty

# Open rofi
riverctl map normal $mod1 R spawn "rofi -show drun"

# Open pcmanfm
riverctl map normal $mod1 N spawn "pcmanfm"

# Open pavucontrol
riverctl map normal $mod1 P spawn "pavucontrol"

# Open discord
riverctl map normal $mod1 D spawn "discord"

# Open spotify
riverctl map normal $mod1 S spawn "spotify"

# Open vscodium
riverctl map normal $mod1 V spawn "vscodium"

# Open multimc
riverctl map normal $mod1 M spawn "multimc"

# Open lollypop
riverctl map normal $mod1 L spawn "lollypop"

# Open ms teams
riverctl map normal $mod1 T spawn "teams-for-linux"

# Open firefox
riverctl map normal $mod1 F spawn "firefox-developer-edition"

# Toggle waybar
riverctl map normal $mod B spawn "killall -SIGUSR1 waybar"

# Open Moc
riverctl map normal $mod M spawn "alacritty -e mocp"

# Reload river configuration
riverctl map normal $mod+Shift R spawn "~/.config/river/init"

# Screenshot
riverctl map normal None Print spawn 'grim -g "$(slurp)" -| wl-copy && notify-send "Screenshot Clipped"'

# Fullscreen
riverctl map normal Shift Print spawn 'IMG=/tmp/$(date | sed "s/\s/-/g" | sed "s/--/-/g").png && grim $IMG && cat $IMG | wl-copy && rm -rf $IMG && notify-send "Full-Screenshot Taken"'

# Close the focused window
riverctl map normal $mod Q close

# Exit river
riverctl map normal $mod+$mod1 R exit

# Shutdown
riverctl map normal $mod+$mod1 Q spawn "shutdown now"

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Toggle float
riverctl map normal $mod T toggle-float

# Toggle fullscreen
riverctl map normal $mod M toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

for mode in normal locked
do
    # Audio 
    #riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    #riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    #riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'volume.sh up'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'volume.sh down'
    riverctl map $mode None XF86AudioMute         spawn 'volume.sh mute'

    # Control screen brightness (using backlight_control)
    #riverctl map $mode None XF86MonBrightnessUp   spawn 'backlight_control +10'
    #riverctl map $mode None XF86MonBrightnessDown spawn 'backlight_control  -10'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightness.sh up'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightness.sh down'
done

# Set background and border color
riverctl border-color-focused 0x69d588
riverctl border-color-unfocused 0x414a5b

# Set repeat rate
# riverctl set-repeat 100 300

riverctl focus-follows-cursor normal

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))
# Toggle the scratchpad with Super+P
riverctl map normal $mod P toggle-focused-tags ${scratch_tag}
# Send windows to the scratchpad with Super+Shift+P
riverctl map normal $mod+Shift P set-view-tags ${scratch_tag}
# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

bash $HOME/.config/river/process.sh
# usage: import-gsettings
config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
if [ ! -f "$config" ]; then exit 1; fi
gnome_schema="org.gnome.desktop.interface"
gtk_theme="$(grep 'gtk-theme-name' "$config" | sed 's/.*\s*=\s*//')"
icon_theme="$(grep 'gtk-icon-theme-name' "$config" | sed 's/.*\s*=\s*//')"
cursor_theme="$(grep 'gtk-cursor-theme-name' "$config" | sed 's/.*\s*=\s*//')"
font_name="$(grep 'gtk-font-name' "$config" | sed 's/.*\s*=\s*//')"
gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" font-name "$font_name"

